### ISSUE TITLE
Home Assistant 0.115: TypeError: __init__() missing 1 required positional argument: 'discovery_data'

### ISSUE THREAD

**Issue by abstractvector** [lukich48/hass_mqtt_template_switch#1]
Home Assistant 0.115 introduced a change in the MQTT library, adding an additional required parameter for instantiating the switch. The error shown in the Home Assistant log is:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mqtt_template/switch.py", line 31, in async_setup_platform
    await _async_setup_entity(hass, config, async_add_entities, discovery_info)
  File "/config/custom_components/mqtt_template/switch.py", line 38, in _async_setup_entity
    async_add_entities([MqttTemplateSwitch(config, config_entry, discovery_data)])
TypeError: __init__() missing 1 required positional argument: 'discovery_data'
```

I have made the fix and will submit a pull request.

**Comment by abstractvector** [comment]
I have submitted pull request #2 to fix this issue.

**Comment by lukich48** [comment]
> I have submitted pull request #2 to fix this issue.

Thank you abstractvector. Sorry for delay, I should tune my email notifications )

**Comment by abstractvector** [comment]
> Thank you abstractvector. Sorry for delay, I should tune my email notifications )

No problem - thanks for merging it! I only found your library about a week ago but it solved my exact use case.
