### ISSUE TITLE
payload_template_off & payload_template_on not working anymore

### ISSUE THREAD

**Issue by vandammesander** [lukich48/hass_mqtt_template_switch#3]
Since the last update it seems that the payload_template_off and payload_template_on settings are removed. Could you please let me know how to migrate my switch to the new way of working?
Example switch configured:

```
- platform: mqtt_template
  name: Smappee plug tv-1
  icon: mdi:power-socket-eu
  state_topic: "servicelocation/<id>/plug/1/state"
  value_template: "{{value_json.value}}"
  command_topic: "servicelocation/<id>/plug/1/setstate"
  payload_template_on: >
                  { 
                   "value" : "ON", 
                   "since" : {{ (as_timestamp(now()) * 1000) | round(0)}}
                  }
  payload_template_off: >
                  { 
                   "value" : "OFF", 
                   "since" : {{ (as_timestamp(now()) * 1000) | round(0)}}
                  }
  payload_on: "ON"
  payload_off: "OFF"

```

**Comment by lukich48** [comment]
Use payload_on and payload_off. These fields now can be templatable. Try
this:

- platform: mqtt_template
  name: Smappee plug tv-1
  icon: mdi:power-socket-eu
  state_topic: "servicelocation/<id>/plug/1/state"
  value_template: "{{value_json.value}}"
  command_topic: "servicelocation/<id>/plug/1/setstate"
  payload_on: >
                  {
                   "value" : "ON",
                   "since" : {{ (as_timestamp(now()) * 1000) | round(0)}}
                  }
  payload_off: >
                  {
                   "value" : "OFF",
                   "since" : {{ (as_timestamp(now()) * 1000) | round(0)}}
                  }
  state_on: "ON"
  state_off: "OFF"

вс, 27 сент. 2020 г., 23:55 vandammesander <notifications@github.com>:
>
> Since the last update it seems that the payload_template_off and
payload_template_on settings are removed. Could you please let me know how
to migrate my switch to the new way of working?

**Comment by vandammesander** [comment]
Thanks @lukich48 that did the trick!
